// Teacher Module Exports
export { default as TeacherDashboard } from './TeacherDashboard'
export { default as ClassManagement } from './ClassManagement'
export { default as GradeManagement } from './GradeManagement'
export { default as ProgressTracking } from './ProgressTracking'
export { default as PredictionView } from './PredictionView'
export { default as PredictionViewV2 } from './pages/PredictionViewV2'
export { default as TeacherReport } from './TeacherReport'
export { default as MessagesNotifications } from './MessagesNotifications'
export { default as ScheduleManagement } from './ScheduleManagement'
export { default as TeacherAppointmentDashboard } from './TeacherAppointmentDashboard'
export { default as AppointmentRequests } from './AppointmentRequests'
export { default as ConfirmedAppointments } from './ConfirmedAppointments'
export { default as StudentSurveyManagement } from './StudentSurveyManagement'
